services:
  postgres:
    image: postgres:16
    container_name: bookitgy-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookitgy
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "55432:5432"

  redis:
    image: redis:7
    container_name: bookitgy-redis
    ports:
      - "6379:6379"

volumes:
  pgdata:

